### ISSUE TITLE
Implement LexicalEntry page

### ISSUE THREAD

**Issue by Andrewdt97** [sil-student-projects/2018-android#15]
Hardcode in entry fields to be replaced later. Main work is with navigation UI.

**Comment by kvlinden** [comment]
See the information collected for sessions under "Project Spec"-"Word list consists of..." here: https://docs.google.com/document/d/1SDjVltO3OHYSosdsOcMd3iQfX241aweJmPP3pJ9X3wY/edit#heading=h.bwne9vf96tl4
Note that we'd eventually like to allow users to press the gloss/audio/image buttons multiple times as needed, adding a new field to the lexical entry each time.
