### ISSUE TITLE
Get Google OAuth2 token working for Android 

### ISSUE THREAD

**Issue by Andrewdt97** [sil-student-projects/2018-android#36]
The basic process for OAuth2 authentication is:
- Do the standard Google OAuth for Android "thing"
- Submit the Oauth token to a languageforge.org API endpoint
- Receive a JWT token for future API calls
- call API using JWT token

**Comment by megahirt** [comment]
this card is all about getting a google OAuth token using the standard Android way of doing Oauth.  The rest (including accessing LF APIs) is another card.
